spring:
  application:
    name: tracking-service

  datasource:
    url: jdbc:postgresql://localhost:5433/tracking_db
    username: postgres
    password: secretpassword

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        missing-queues-fatal: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
